languages_to_include = [
    ('ar', 'Arabic', 'arz', 145, False),
    ('bg', 'Bulgarian', 'bul', 84, False),
    ('bn', 'Bengali', 'ben', 53, False),
    ('cs', 'Czech', 'ces', 58, True),
    ('de', 'German', 'deu', 157, True),
    ('el', 'Greek', 'ell', 155, False),
    ('es', 'Spanish', 'spa', 155, True),
    ('et', 'Estonian', 'ekk', 60, True),
    ('fa', 'Persian', 'pes', 147, False),
    ('fi', 'Finnish', 'fin', 155, True),
    ('fr', 'French', 'fra', 158, True),
    ('gu', 'Gujarati', 'guj', 40, False),
    ('hi', 'Hindi', 'hin', 144, False),
    ('hr', 'Croatian', 'hbs', 60, True),
    ('hu', 'Hungarian', 'hun', 155, True),
    ('id', 'Indonesian', 'ind', 153, True),
    ('ig', 'Igbo', 'ibo', 95, True),
    ('is', 'Icelandic', 'isl', 77, True),
    ('it', 'Italian', 'ita', 81, True),
    ('kn', 'Kannada', 'kan', 145, False),
    ('ko', 'Korean', 'kor', 149, False),
    ('ky', 'Kyrgyz', 'kir', 40, False),
    ('lt', 'Lithuanian', 'lit', 80, True),
    ('lv', 'Latvian', 'lav', 126, True),
    ('mk', 'Macedonian', 'mkd', 38, False),
    ('ml', 'Malayalam', 'mal', 68, False),
    ('mr', 'Marathi', 'mar', 72, False),
    ('nl', 'Dutch', 'nld', 89, True),
    ('pl', 'Polish', 'pol', 89, True),
    ('pt', 'Portuguese', 'por', 59, True),
    ('ro', 'Romanian', 'ron', 82, True),
    ('ru', 'Russian', 'rus', 156, False),
    ('sw', 'Swahili', 'swh', 142, True),
    ('ta', 'Tamil', 'tam', 83, False),
    ('te', 'Telugu', 'tel', 64, False),
    ('tl', 'Tagalog', 'tgl', 145, True),
    ('tr', 'Turkish', 'tur', 154, True),
    ('uk', 'Ukrainian', 'ukr', 56, False),
    ('yo', 'Yoruba', 'yor', 140, True),
    # No JusText:
    ('am', None, 'amh', 99, False),
    ('ha', None, 'hau', 148, True),
    ('ja', None, 'jpn', 151, False),
    ('om', None, 'hae', 152, True),
    ('or', None, 'ory', 30, False),
    ('pa', None, 'pan', 76, False),
    ('ps', None, 'pst', 69, False),
    ('sn', None, 'sna', 48, True),
    ('ti', None, 'tir', 36, False),
    ('zh', None, 'cmn', 153, False),
    # English not needed here:
    # ('en', 'English', 'eng', 159, True),
    # Found to be too noisy:
    # ('rw', None, 'kin', 34, True),
    # ('so', None, 'som', 87, True),
    # No Google Translate support:
    # ('nr', None, 'nde', 37, True),
    # Too similar to other languages:
    # ('sr', 'Serbian', 'hbs', 60, False),
    # ('kk', 'Kazakh', 'kaz', 9, False),
    # ('bs', 'Bosnian', 'bos', 1, True),
    # Too less WALS features:
    # ('af', 'Afrikaans', 'afr', 16, True),
    ]
